### ISSUE TITLE
Net standard 2.1 support

### ISSUE THREAD

**Issue by Nice3point** [dosymep/Serilog.Sinks.Autodesk.Revit#1]
Is .Net standard 2.1 support planned for this package? Revit 2025 still works, but warnings appear during compilation

**Comment by Nice3point** [comment]
Serilog.Sinks.Console supported frameworks
![изображение](https://github.com/dosymep/Serilog.Sinks.Autodesk.Revit/assets/20504884/4ab2bf4c-51c9-43ba-a39c-6fb320ba4a2a)

**Comment by dosymep** [comment]
Yes, I'm planning to update the library

**Comment by Nice3point** [comment]
Great, thanks
