### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by Nice3point** [dosymep/Serilog.Sinks.Autodesk.Revit#5]
gitignore text in the Readme incorrectly inserted

https://github.com/dosymep/Serilog.Sinks.Autodesk.Revit/blob/master/README.md?plain=1#L25

![изображение](https://github.com/dosymep/Serilog.Sinks.Autodesk.Revit/assets/20504884/d94bccf7-29d4-47dc-a4df-56e001618c75)

**Comment by dosymep** [comment]
thanks for report
